# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: first job
    steps:
    - script: echo first job Hello, world!
    displayName: 'Run a one-line script'

  - job: second job
    steps:
    - script: echo second job Hello, world!
    displayName: 'Run a one-line script'

