# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build 
  jobs:
  - job: first_job
    steps:
    - script: echo first job Hello, world!
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(System.DefaultWorkingDirectory)
    displayName: 'Run a one-line script'

  - job: second_job
    steps:
    - script: echo second job Hello, world!
    displayName: 'Run a one-line script'
- stage: DevDeployment
  jobs:
  - job: deploy_dev
    steps:
    - bash: echo devdeploy
- stage: QADeployment
  dependsOn:
  - build
  jobs:
  - job: deploy_qa
    steps:
    - bash: echo qadeploy
- stage: prodDeployment
  dependsOn:
  - DevDeployment
  - QADeployment 
  jobs:
  - job: deploy_prod
    steps:
    - bash: echo proddeploy