# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - jobs: first job
    steps:
    - script: echo first job Hello, world!
    displayName: 'Run a one-line script'

  - jobs: second job
    steps:
    - script: echo second job Hello, world!
    displayName: 'Run a one-line script'
    - script: |
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
